### PR TITLE
Switch to Dropbox API v2

### PR DESCRIPTION
**Pull request by vladholubiev**
Hey @gcampax. It's been a while since Dropbox introduced their API v2.
Apart from some refactoring and switching from obsolete Meteor methods, the key change is here: 

``` diff
-var getIdentity = function (accessToken) {
-  try {
-    return Meteor.http.get("https://api.dropbox.com/1/account/info", {
+var getAccountInfo = function (accessToken) {
+    var hostname = 'https://api.dropboxapi.com/2/users/get_current_account';
```

### CODE REVIEW

**Comment by gcampax** [comment]
I have no way to test this code because I'm no longer using meteor, but I'm happy to merge it.

**Comment by vladholubiev** [comment]
It's been a while, but thanks anyway!

**Comment by gcampax** [comment]
I know I'm sorry, I don't really maintain this package anymore. I will be happy to transfer to someone more actively committed to it.

**Comment by vladholubiev** [comment]
Would be really great. I'm running it in production, so it's in my interest to maintain it :smile: 

Here are some links to look at as the next steps:
- http://docs.meteor.com/commandline.html#meteoradmin
- https://help.github.com/articles/inviting-collaborators-to-a-personal-repository/

**Comment by vladholubiev** [comment]
@gcampax can you add my atmosphere account (`vladgolubev`) as package collaborator?

```
=> Errors while publishing:                   

While pre-publishing package gcampax:dropbox-oauth:
error: You are not an authorized maintainer for this package.
```

**Pull request merged**
